resources:
  - kind: file
    selector:
      query: 'true'
      files:
        - path: '**/*playlist.json'
    port:
      entity:
        mappings:
          identifier: .id
          title: .snippet.title
          blueprint: '"youtube_playlist"'
          properties:
            kind: .kind
            etag: .etag
            publishedAt: .snippet.publishedAt
            channelId: .snippet.channelId
            description: .snippet.description
            thumbnails: .snippet.thumbnails
            channelTitle: .snippet.channelTitle
            defaultLanguage: .snippet.defaultLanguage
            privacyStatus: .status.privacyStatus
            podcastStatus: .status.podcastStatus
            itemCount: .contentDetails.itemCount
            embedHtml: .player.embedHtml
            localizations: .localizations
